[package]
name = "id-set"
description = "Bitset implementation."
documentation = "https://docs.rs/id-set/0.1.2/id_set"
repository = "https://github.com/andrewhickman/id-set"
license = "MIT"
version = "0.1.2"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]